spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Exo-ecommerce-spring-freemarker-postgres
    username: postgres
    password: Postgres003322*/
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # attention !!!!!! si je fais "create" ca va réinitialiser la bdd

      ddl-auto: update
    #   afficher sql
    show-sql: true
    properties:
      hibernate:
        #       formatter le sql generer
        format_sql: true

server:
  port: 8080